// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.API.Models;

#nullable disable

namespace Shop.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241118110618_AddInitialData")]
    partial class AddInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "4135803517878",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 829.69211569320976,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gorgeous Wooden Chair"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "6803006536917",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 136.24926863901749,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Generic Metal Car"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "6170030750344",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 419.39507149923367,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Refined Wooden Fish"
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "4125416944444",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 131.31670311853136,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fantastic Concrete Bacon"
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "0970650659319",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 214.24055093724306,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gorgeous Rubber Keyboard"
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "6529290068629",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 708.6934623945009,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Small Cotton Computer"
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "1800862881385",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 181.36082924313882,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gorgeous Cotton Keyboard"
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "9592797096348",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 557.22589721168663,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Practical Steel Gloves"
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "2236899047712",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 820.03939995311168,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Incredible Rubber Bike"
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "4528392089848",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 684.27186477522923,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Intelligent Soft Gloves"
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "8079060231985",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 594.96452395523181,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sleek Rubber Computer"
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "0669820509058",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 647.12403275544011,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Licensed Fresh Car"
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "9237492608327",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 624.90486521735079,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Unbranded Wooden Soap"
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "5446087306966",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 860.2957212493269,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Small Steel Pizza"
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "9898673383732",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 149.8611582894163,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sleek Frozen Pants"
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "6179936432293",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 41.4314823357535,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Small Fresh Bike"
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "1019870314994",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 890.5148672757274,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Awesome Fresh Sausages"
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "3281043334131",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 431.1791396155856,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Small Soft Fish"
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "7220837679658",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 121.94656162287414,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gorgeous Granite Cheese"
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "5767158553899",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 121.02393029864129,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fantastic Granite Towels"
                        },
                        new
                        {
                            Id = 21,
                            Barcode = "9403581525787",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 891.07206650174783,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Unbranded Frozen Mouse"
                        },
                        new
                        {
                            Id = 22,
                            Barcode = "9014664420860",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 150.44004214435819,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tasty Frozen Towels"
                        },
                        new
                        {
                            Id = 23,
                            Barcode = "5067095180173",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 475.13188163290357,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Refined Frozen Shoes"
                        },
                        new
                        {
                            Id = 24,
                            Barcode = "0104385927294",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 763.56302413882827,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Awesome Cotton Gloves"
                        },
                        new
                        {
                            Id = 25,
                            Barcode = "4504815286377",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 478.91523904302869,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Practical Rubber Bike"
                        },
                        new
                        {
                            Id = 26,
                            Barcode = "9339120881215",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 74.051527644531575,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Handmade Metal Towels"
                        },
                        new
                        {
                            Id = 27,
                            Barcode = "9823104151222",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 84.032778956942622,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Practical Cotton Salad"
                        },
                        new
                        {
                            Id = 28,
                            Barcode = "6814229609203",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 357.52829439822972,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sleek Steel Chicken"
                        },
                        new
                        {
                            Id = 29,
                            Barcode = "7797738860763",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 643.07406103241919,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fantastic Concrete Table"
                        },
                        new
                        {
                            Id = 30,
                            Barcode = "7006653700208",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 63.614898659575211,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Incredible Wooden Soap"
                        },
                        new
                        {
                            Id = 31,
                            Barcode = "2966952662100",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 867.34741706137891,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rustic Frozen Pizza"
                        },
                        new
                        {
                            Id = 32,
                            Barcode = "4430026962673",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 322.70866367952368,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Licensed Fresh Tuna"
                        },
                        new
                        {
                            Id = 33,
                            Barcode = "8684847902172",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 433.71145619717959,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sleek Steel Sausages"
                        },
                        new
                        {
                            Id = 34,
                            Barcode = "5438269622698",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 827.45005094467206,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Incredible Concrete Towels"
                        },
                        new
                        {
                            Id = 35,
                            Barcode = "9978695199525",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 338.55159992005281,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rustic Wooden Ball"
                        },
                        new
                        {
                            Id = 36,
                            Barcode = "5456608751199",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 662.42108751433955,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fantastic Steel Computer"
                        },
                        new
                        {
                            Id = 37,
                            Barcode = "2579847727442",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 974.5654807722035,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Unbranded Wooden Pizza"
                        },
                        new
                        {
                            Id = 38,
                            Barcode = "6767398108414",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 467.51950786193811,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Unbranded Plastic Towels"
                        },
                        new
                        {
                            Id = 39,
                            Barcode = "7537707833332",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 386.02067984920961,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Small Fresh Tuna"
                        },
                        new
                        {
                            Id = 40,
                            Barcode = "4002869876358",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 473.97394598739874,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Handcrafted Fresh Soap"
                        },
                        new
                        {
                            Id = 41,
                            Barcode = "5047978806475",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 509.88383010955704,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rustic Fresh Bacon"
                        },
                        new
                        {
                            Id = 42,
                            Barcode = "3561884993439",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 583.8249252991867,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Practical Frozen Pizza"
                        },
                        new
                        {
                            Id = 43,
                            Barcode = "3577531489408",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 158.36421467939587,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Intelligent Cotton Towels"
                        },
                        new
                        {
                            Id = 44,
                            Barcode = "5223619893343",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 589.19982115048902,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Incredible Metal Shoes"
                        },
                        new
                        {
                            Id = 45,
                            Barcode = "5228724708094",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 269.05001498900816,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Licensed Concrete Sausages"
                        },
                        new
                        {
                            Id = 46,
                            Barcode = "8327748969799",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 616.70941943522052,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Generic Metal Sausages"
                        },
                        new
                        {
                            Id = 47,
                            Barcode = "1227707662983",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 65.019721532249704,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ergonomic Soft Hat"
                        },
                        new
                        {
                            Id = 48,
                            Barcode = "3694884912688",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 184.72559618564586,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Incredible Metal Table"
                        },
                        new
                        {
                            Id = 49,
                            Barcode = "5768134111805",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 552.4624730993354,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tasty Wooden Hat"
                        },
                        new
                        {
                            Id = 50,
                            Barcode = "4875337867185",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 884.29157508783578,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gorgeous Plastic Pants"
                        },
                        new
                        {
                            Id = 51,
                            Barcode = "1603134376585",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 792.91939277105007,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Handcrafted Wooden Table"
                        },
                        new
                        {
                            Id = 52,
                            Barcode = "6649138045336",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 66.205732664189171,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Refined Steel Ball"
                        },
                        new
                        {
                            Id = 53,
                            Barcode = "1625252267194",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 491.4547220549801,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Practical Steel Shoes"
                        },
                        new
                        {
                            Id = 54,
                            Barcode = "5828932277193",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 598.82490147921476,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Licensed Metal Salad"
                        },
                        new
                        {
                            Id = 55,
                            Barcode = "8524302656618",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 350.54359373429025,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gorgeous Rubber Computer"
                        },
                        new
                        {
                            Id = 56,
                            Barcode = "5616130358024",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 861.54531531946054,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Handcrafted Fresh Table"
                        },
                        new
                        {
                            Id = 57,
                            Barcode = "8311189147519",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 465.46177874107929,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fantastic Steel Car"
                        },
                        new
                        {
                            Id = 58,
                            Barcode = "0446721181145",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 380.92345042849121,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ergonomic Fresh Fish"
                        },
                        new
                        {
                            Id = 59,
                            Barcode = "0187381575416",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 183.72819443360353,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Intelligent Granite Towels"
                        },
                        new
                        {
                            Id = 60,
                            Barcode = "9597009936771",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 5.0901571819978564,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sleek Frozen Gloves"
                        },
                        new
                        {
                            Id = 61,
                            Barcode = "8606762106695",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 898.397511797211,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Intelligent Wooden Chair"
                        },
                        new
                        {
                            Id = 62,
                            Barcode = "5974909801387",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 180.51852417807959,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Incredible Concrete Pizza"
                        },
                        new
                        {
                            Id = 63,
                            Barcode = "1723297603295",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 573.80863870857695,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sleek Cotton Shoes"
                        },
                        new
                        {
                            Id = 64,
                            Barcode = "6064851864833",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 41.934165286335237,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Small Granite Sausages"
                        },
                        new
                        {
                            Id = 65,
                            Barcode = "0198200797681",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 757.79967412296662,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sleek Concrete Mouse"
                        },
                        new
                        {
                            Id = 66,
                            Barcode = "7310210564821",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 471.23339342243662,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Small Soft Table"
                        },
                        new
                        {
                            Id = 67,
                            Barcode = "4862306797499",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 255.68489719726372,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Awesome Steel Computer"
                        },
                        new
                        {
                            Id = 68,
                            Barcode = "4806798265142",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 42.821179837836503,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Generic Metal Table"
                        },
                        new
                        {
                            Id = 69,
                            Barcode = "3552425324652",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 776.80525399316343,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fantastic Metal Towels"
                        },
                        new
                        {
                            Id = 70,
                            Barcode = "5275688965520",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 493.66506883532975,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tasty Soft Table"
                        },
                        new
                        {
                            Id = 71,
                            Barcode = "4858055354267",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 858.81639124956746,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Generic Steel Salad"
                        },
                        new
                        {
                            Id = 72,
                            Barcode = "1321676277916",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 882.6857174600874,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Handcrafted Soft Fish"
                        },
                        new
                        {
                            Id = 73,
                            Barcode = "3556572214637",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 116.689460747265,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Handcrafted Cotton Fish"
                        },
                        new
                        {
                            Id = 74,
                            Barcode = "9566718528515",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 716.42358648237939,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tasty Fresh Bacon"
                        },
                        new
                        {
                            Id = 75,
                            Barcode = "3171550953089",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 580.86470317275473,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Refined Wooden Hat"
                        },
                        new
                        {
                            Id = 76,
                            Barcode = "4104646139608",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 962.02758268175069,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Licensed Fresh Mouse"
                        },
                        new
                        {
                            Id = 77,
                            Barcode = "4625495718863",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 392.5458063108594,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gorgeous Plastic Computer"
                        },
                        new
                        {
                            Id = 78,
                            Barcode = "6381770016380",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 877.84281514018903,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fantastic Frozen Pants"
                        },
                        new
                        {
                            Id = 79,
                            Barcode = "4504015755840",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 425.69537124070121,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Incredible Steel Sausages"
                        },
                        new
                        {
                            Id = 80,
                            Barcode = "6742791423180",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 385.23291431937037,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Unbranded Steel Gloves"
                        },
                        new
                        {
                            Id = 81,
                            Barcode = "4894623321163",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 984.15386507434482,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Licensed Fresh Salad"
                        },
                        new
                        {
                            Id = 82,
                            Barcode = "3291768088387",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 946.98884686734016,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gorgeous Metal Car"
                        },
                        new
                        {
                            Id = 83,
                            Barcode = "5519051847076",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 953.96033969705934,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Handmade Metal Chips"
                        },
                        new
                        {
                            Id = 84,
                            Barcode = "4618721473056",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 841.90270586260715,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tasty Metal Keyboard"
                        },
                        new
                        {
                            Id = 85,
                            Barcode = "0559378228726",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 298.92139472110262,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sleek Cotton Mouse"
                        },
                        new
                        {
                            Id = 86,
                            Barcode = "2201720521136",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 892.90532059031784,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Refined Wooden Bike"
                        },
                        new
                        {
                            Id = 87,
                            Barcode = "5568193553314",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 664.73058655566103,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Small Plastic Pizza"
                        },
                        new
                        {
                            Id = 88,
                            Barcode = "2841324405793",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 588.09672927814381,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Unbranded Concrete Cheese"
                        },
                        new
                        {
                            Id = 89,
                            Barcode = "5610036529731",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 201.07776998313039,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Intelligent Rubber Sausages"
                        },
                        new
                        {
                            Id = 90,
                            Barcode = "0984231303669",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 432.09319924520946,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Incredible Fresh Pants"
                        },
                        new
                        {
                            Id = 91,
                            Barcode = "7165157502708",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 718.83903196679387,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Incredible Metal Shirt"
                        },
                        new
                        {
                            Id = 92,
                            Barcode = "5907229699099",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 771.37464212690236,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Handmade Metal Shirt"
                        },
                        new
                        {
                            Id = 93,
                            Barcode = "1288931820426",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 616.58239172193328,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Unbranded Concrete Pants"
                        },
                        new
                        {
                            Id = 94,
                            Barcode = "1310487815660",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 559.67407292997189,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fantastic Metal Bike"
                        },
                        new
                        {
                            Id = 95,
                            Barcode = "5148568802539",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 116.65926629475284,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rustic Frozen Pants"
                        },
                        new
                        {
                            Id = 96,
                            Barcode = "0996731077520",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 365.43258493739768,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Generic Plastic Salad"
                        },
                        new
                        {
                            Id = 97,
                            Barcode = "1076573146154",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 248.18219422557493,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ergonomic Steel Computer"
                        },
                        new
                        {
                            Id = 98,
                            Barcode = "8395883888350",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 763.69709537909239,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sleek Plastic Cheese"
                        },
                        new
                        {
                            Id = 99,
                            Barcode = "2886526427945",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 375.65533092927905,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Unbranded Wooden Table"
                        },
                        new
                        {
                            Id = 100,
                            Barcode = "1747214879969",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 347.04380050489857,
                            ReleaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gorgeous Granite Bacon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
